/**
 * Created by Carlos on 13/08/2016.
 */
export const ActionTypes = {
    SET_GRADE:"SET_GRADE",
    SET_TEAM:"SET_TEAM",
    SET_GAME:"SET_GAME",
    TOGGLE_TEAM:"TOGGLE_TEAM",
    INIT_STATE:"INIT_STATE",
    EXCLUDE_PLAYER:"EXCLUDE_PLAYER",
    INCLUDE_PLAYER:"INCLUDE_PLAYER",
    BUILD_TEAMS:"BUILD_TEAMS",
    ORDERBY_SUMMARY:"ORDERBY_SUMMARY",
    ORDERBY_GAME:"ORDERBY_GAME"
};
